-- Criar tabela de categorias primeiro
create table categorias (
  id bigint generated by default as identity primary key,
  nome text not null unique,
  emoji text
);

-- Criar tabela de produtos vinculada às categorias
create table produtos (
  id bigint generated by default as identity primary key,
  nome text not null,
  preco decimal(10,2) not null,
  imagem_url text,
  categoria_nome text references categorias(nome),
  disponivel boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Inserir as categorias iniciais do Point Maciel
insert into categorias (nome, emoji) values 
('Cuscuz', '🍲'), 
('Hambúrguer', '🍔'), 
('Sorvetes', '🍦'), 
('Sucos', '🥤'),
('Refrigerantes', '🥤');
 //
-- 1. Criar o bucket se ele não existir
insert into storage.buckets (id, name, public)
values ('produtos', 'produtos', true)
on conflict (id) do nothing;

-- 2. Liberar SELECT para todo mundo (clientes verem as fotos)
create policy "Acesso Público para Fotos"
on storage.objects for select
using ( bucket_id = 'produtos' );

-- 3. Liberar INSERT para usuários logados (Maciel subir fotos)
create policy "Admin pode subir fotos"
on storage.objects for insert
with check (
  bucket_id = 'produtos' 
  and auth.role() = 'authenticated'
);

-- 4. Liberar UPDATE para usuários logados (Maciel trocar fotos)
create policy "Admin pode atualizar fotos"
on storage.objects for update
using ( bucket_id = 'produtos' )
with check ( auth.role() = 'authenticated' );

-- 5. Liberar DELETE para usuários logados (Maciel apagar fotos)
create policy "Admin pode deletar fotos"
on storage.objects for delete
using ( bucket_id = 'produtos' and auth.role() = 'authenticated' );
//
-- 1. Habilitar RLS na tabela (se não estiver)
alter table public.produtos enable row level security;

-- 2. Permitir que QUALQUER UM veja os produtos (Vitrine/Home)
create policy "Acesso público para leitura" 
on public.produtos for select 
using (true);

-- 3. Permitir que apenas o ADMIN (logado) insira produtos
create policy "Admin pode inserir produtos" 
on public.produtos for insert 
with check (auth.role() = 'authenticated');

-- 4. Permitir que apenas o ADMIN (logado) atualize produtos
create policy "Admin pode atualizar produtos" 
on public.produtos for update 
using (auth.role() = 'authenticated');

-- 5. Permitir que apenas o ADMIN (logado) delete produtos
create policy "Admin pode deletar produtos" 
on public.produtos for delete 
using (auth.role() = 'authenticated');
//
-- Adiciona a coluna 'image' na tabela produtos
alter table public.produtos 
add column if not exists image text;

-- (Opcional) Se você ainda não tem a coluna 'emoji', aproveite para adicionar:
alter table public.produtos 
add column if not exists emoji text;